source:
    source: Database
    url: 'postgresql://postgres:@localhost:5432/slashdb'
    statement: 'SELECT url, parsed_url FROM source_refs'
    fields:
        - name: key
          type: String
          map: url
        - name: value
          type: String
          map: parsed_url

manipulations:
  - filter: refly_etl.modifiers.UniqueField
    field: key

target:
  type: CSV
  resource: urls.csv
  delimiter: "|"
  addHeader: false
  appendFile: false
