source:
    source: Database
    url: 'postgresql://postgres:@localhost:5432/slashdb'
    statement: 'SELECT name, parent, uri, parsed_uri, content, docset, alias, type FROM source_refs'
    fields:
        - name: reference
          type: String
          map: name
        - name: content
          type: String
        - name: uri
          type: String
          map: parsed_uri
          key: true
        - name: parent
          type: String
        - name: type
          type: String
        - name: docset
          type: String
          key: true

manipulations:
  - modifier: refly_etl.modifiers.RepairLinks
    field: content
    file: urlerrors.csv
    regex: |
        \n\n\[\d*\]: ([\.:?=/\w\-#~,\.; \@\(\)]*)  
  - modifier: refly_etl.modifiers.ReplaceByDictFile
    field: content
    file: urls.csv 
  - filter: refly_etl.modifiers.UniqueField
    field: uri

target:
  type: Database
  url: postgresql://postgres@127.0.0.1:5432/slashdb
  table: temp_refs
  createTable: false
  truncateTable: false
  continueOnError: false

